Problem 1-(b)
===========

In [64]:
x = [[880, 214],
[43, 203],
[270, 197],
[886, 347],
[745, 302],
[943, 128],
[476, 590],
[419, 214],
[317, 335],
[783, 521],
[235, 427],
[665, 429],
[655, 362],
[427, 333],
[412, 415],
[746, 351],
[434, 415],
[525, 234],
[716,308],
[602, 187]]

X = [[312.747, 309.140, 30.086],
[305.796, 311.649, 30.356],
[307.694, 312.358, 30.418],
[310.149, 307.186, 29.298],
[311.937, 310.105, 29.216],
[311.202, 307.572, 30.682],
[307.106, 306.876, 28.660],
[309.317, 312.490, 30.230],
[307.435, 310.151, 29.318],
[308.253, 306.300, 28.881],
[306.650, 309.301, 28.905],
[308.069, 306.831, 29.189],
[309.671, 308.834, 29.029],
[308.255, 309.955, 29.267],
[307.546, 308.613, 28.963],
[311.036, 309.206, 28.913],
[307.518, 308.175, 29.069],
[309.950, 311.262, 29.990],
[312.160, 310.772, 29.080],
[311.988, 312.709, 30.514]]


A = []
for i in range(len(X)):
    xx = X[i]
    u,v = x[i]
    A.append(
        [xx[0], xx[1], xx[2],1,0,0,0,0,-u*xx[0], -u*xx[1], -u*xx[2], -u]
    )
    A.append(
        [0,0,0,0,xx[0], xx[1], xx[2],1,-v*xx[0], -v*xx[1], -v*xx[2], -v ]
    )
import numpy as np
A = np.array(A)
[U,S,V] = np.linalg.svd(A)
p = V[-1,:]
P_1 = p.reshape((3,4))
print(P_1)

[[ 3.09963996e-03  1.46204548e-04 -4.48497465e-04 -9.78930678e-01]
 [ 3.07018252e-04  6.37193664e-04 -2.77356178e-03 -2.04144405e-01]
 [ 1.67933533e-06  2.74767684e-06 -6.83964827e-07 -1.32882928e-03]]


Problem 1-(c)
=========

In [65]:
def pseudo_inverse(A):
    return np.linalg.pinv(A)

A = []
b = []
for i in range(len(X)):
    xx = X[i]
    u,v = x[i]
    A.append(
        [xx[0], xx[1], xx[2],1,0,0,0,0,-u*xx[0], -u*xx[1], -u*xx[2]]
    )
    A.append(
        [0,0,0,0,xx[0], xx[1], xx[2],1,-v*xx[0], -v*xx[1], -v*xx[2]]
    )
    b.append(u)
    b.append(v)

A = np.array(A)
b = np.array(b)
p = np.matmul(pseudo_inverse(A),b)
p = np.append(p,1)
P_2 = p.reshape((3,4))
print(P_2)

[[-2.33259098e+00 -1.09993113e-01  3.37413916e-01  7.36673920e+02]
 [-2.31050254e-01 -4.79506029e-01  2.08717636e+00  1.53627756e+02]
 [-1.26379606e-03 -2.06770917e-03  5.14635233e-04  1.00000000e+00]]


In [69]:
print(P_2[-1,-1]/P_1[-1,-1]*P_1)

[[-2.33260962e+00 -1.10025080e-01  3.37513233e-01  7.36686567e+02]
 [-2.31044166e-01 -4.79515070e-01  2.08722206e+00  1.53627263e+02]
 [-1.26377057e-03 -2.06774255e-03  5.14712341e-04  1.00000000e+00]]
